### ISSUE TITLE
Some translation problems can't determine the exact meaning of some sentence.

### ISSUE THREAD

**Issue by vecStardo** [kmy0/Anomaly_Investigations_Editor#1]
Some translation problems can't determine the exact meaning of some sentence.
 

"Works only when edting single setting" it in config_menu.lua line 233, I guess this sentence means that this setting is only valid when modified separately, but this option is in the multitasking editing menu.

 in config_menu.lua 536~542 I can't understand the meaning of these sentences.
“Always None below 2 Target Num on Extra Maps"
I think this sentence means that more than two targets are not allowed on additional maps. But I tried to edit it like this, and it showed that it passed.
“Always None below 4 Target Num"
Does this sentence mean that only when the target number is greater than 4 is available?
"Always None above 2 Target Num"
Does this sentence mean that only when the target number is less than 2 is available?

**Comment by kmy0** [comment]
> "Works only when edting single setting" it in config_menu.lua line 233, I guess this sentence means that this setting is only valid when modified separately, but this option is in the multitasking editing menu.

...
> “Always None below 2 Target Num on Extra Maps"
I think this sentence means that more than two targets are not allowed on additional maps

This means that when Target Num setting is set to 1 on Infernal Springs, Arena and Forlorn Arena, Monster 2 setting is forced to None, meaning only one monster can be present on those maps.

**Comment by kmy0** [comment]
> "Works only when editing single setting" it in config_menu.lua line 233, I guess this sentence means that this setting is only valid when modified separately, but this option is in the multitasking editing menu.

When Keep Valid is selected you can edit only one setting. Thats because its hard to make sure that all parameters are within valid range when changing more than one setting at the same time.


"None" is one of the options in the monster list. When Monster setting is set to "None" it means that this monster slot will be empty.

> “Always None below x Target Num"

This means that this particular Monster slot is forced to be empty when Target Num is set to smaller number than x.

> “Always None below 2 Target Num on Extra Maps"

Same as above, but only on Extra Maps (Infernal Springs, Arena or Forlorn Arena)
